import {
  AccountBox,
  Business,
  Dashboard,
  History,
  Logout,
  AccountBalanceWalletOutlined,
  DownloadingOutlined,
  MoneyOutlined,
  AccountBoxOutlined,
  AccountCircleOutlined,
  Menu,
  Apps,
  RequestPage,
  RequestQuote,
  Settings,
  List,
} from "@mui/icons-material";
import { ROUTES } from "../../../../constants/route-links";

export const MSideBarData = [
  {
    title: "List",
    url: ROUTES.list.url,
    route: ROUTES.list.route,
    icon: <List />,
    group: 1,
    text: "list",
  },
  {
    title: "Request",
    url: ROUTES.request.url,
    route: ROUTES.request.route,
    icon: <RequestQuote />,
    group: 1,
    text: "request",
  },
  {
    title: "Payment",
    url: ROUTES.payment.url,
    route: ROUTES.payment.route,
    icon: <AccountBalanceWalletOutlined />,
    group: 1,
    text: "payment",
  },
  {
    title: "More...",
    url: ROUTES.apps.url,
    route: ROUTES.apps.route,
    icon: <Apps />,
    group: 1,
    text: "actions",
  },
  {
    title: "Settings",
    url: ROUTES.settings.url,
    route: ROUTES.settings.route,
    icon: <Settings />,
    group: 1,
    text: "settings",
  },

  {
    title: "Logout",
    url: ROUTES.base.url,
    route: ROUTES.base.route,
    icon: <Logout />,
    group: 2,
  },
];
